name = "iipython-os"
pages_build_output_dir = "dist"
compatibility_date = "2024-10-01"

# Installing manually so I don't need pyproject.toml
[env.production.vars]
UNSTABLE_PRE_BUILD = "pip install nova-framework"
