name = "iipython-remote"
main = "index.js"
compatibility_date = "2024-11-11"

# Fuck off Cloudflare
workers_dev = false
send_metrics = false

# Custom domain
routes = [
  { pattern = "remote.iipython.dev", custom_domain = true }
]

[vars]
PUBLIC_URL = "https://remote.iipython.dev"
